// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/hokkung/configuration/server"
	server2 "github.com/hokkung/srv/server"
)

// Injectors from wire.go:

func InitializeApplication() (*ApplicationAPI, func(), error) {
	serverCustomizer, cleanup, err := server.ProvideCustomizer()
	if err != nil {
		return nil, nil, err
	}
	serverServer, cleanup2, err := server2.ProvideServer(serverCustomizer)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	applicationAPI := &ApplicationAPI{
		Server: serverServer,
	}
	return applicationAPI, func() {
		cleanup2()
		cleanup()
	}, nil
}
